name: Build
on:
  push:
    branches:
      - main
    paths:
      - "!docs/**"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # 自动取消其他运行中的workflow
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{secrets.REPO_TOKEN}}
    steps:
      - name: Setup timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "latest"
      - name: Get dependencies and build
        run: |
          npm install -g pnpm@latest-10
          pnpm install
          pnpm run build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Push update to subconverter
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v8
        with:
          github-token: ${{env.GIT_TOKEN}}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'subconverter',
              workflow_id: 'submodule.yml',
              ref: 'main',
            });
